name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node and npm
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@cinch-labs'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: v1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
      - run: |
          npm run test
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Configure node and npm
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@cinch-labs'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: v1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
      - run: npm run build
      - run: npm run package
      - uses: ./
        with:
          file: ./links.yml
